
# p = Post.create(title: 'First Post', text: 'First post who this', date: '06/01/21')

t0= Tag.create(name: "Angry")
t1= Tag.create(name: "Anxious")
t2= Tag.create(name: "Betrayed")
t3= Tag.create(name: "Conflicted")
t4= Tag.create(name: "Challenged")
t5= Tag.create(name: "Excited")
t6= Tag.create(name: "Family")
t7= Tag.create(name: "Friends")
t8= Tag.create(name: "Happy")
t9= Tag.create(name: "Jealous")
t10= Tag.create(name: "Lonely")
t11= Tag.create(name: "New Changes")
t12= Tag.create(name: "Relationships")
t13= Tag.create(name: "Sad")
t14= Tag.create(name: "Talk to Therapist")
t15= Tag.create(name: "Upset")

# # PostTag.create(post_id: p.id, :tag_id => [t4.id, t5.id, t3.id, t2.id])
# PostTag.create(post_id: p.id, tag_id: t5.id)
# PostTag.create(post_id: p.id, tag_id: t3.id)
# PostTag.create(post_id: p.id, tag_id: t2.id)
